[package]
name = "apx-shim"
version = "0.1.0"
edition = "2021"
description = "Apx interop library"

[dependencies]
anyhow = "1.0.95"
duct = "0.13.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
which = "7.0.1"
